// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApFUUXuW6i6dXkbHOpUymqhFXoR8frSMA',
    appId: '1:694539643985:web:aa82680552c33e29b41c70',
    messagingSenderId: '694539643985',
    projectId: 'agridirect-34e78',
    authDomain: 'agridirect-34e78.firebaseapp.com',
    storageBucket: 'agridirect-34e78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh9qKuPRxXJ6fbOOD-qFbjtUQzYOs0I-8',
    appId: '1:694539643985:android:95d0a30f0db63757b41c70',
    messagingSenderId: '694539643985',
    projectId: 'agridirect-34e78',
    storageBucket: 'agridirect-34e78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0CP3rBrMPfEiGoRN9IqmAbQpjYRNoNA',
    appId: '1:694539643985:ios:9c8336a47686c052b41c70',
    messagingSenderId: '694539643985',
    projectId: 'agridirect-34e78',
    storageBucket: 'agridirect-34e78.firebasestorage.app',
    iosClientId: '694539643985-tpnrmi9qp937ro5s4id1a8agsfvp0v9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriDirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0CP3rBrMPfEiGoRN9IqmAbQpjYRNoNA',
    appId: '1:694539643985:ios:9c8336a47686c052b41c70',
    messagingSenderId: '694539643985',
    projectId: 'agridirect-34e78',
    storageBucket: 'agridirect-34e78.firebasestorage.app',
    iosClientId: '694539643985-tpnrmi9qp937ro5s4id1a8agsfvp0v9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriDirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApFUUXuW6i6dXkbHOpUymqhFXoR8frSMA',
    appId: '1:694539643985:web:07743a824940cc4cb41c70',
    messagingSenderId: '694539643985',
    projectId: 'agridirect-34e78',
    authDomain: 'agridirect-34e78.firebaseapp.com',
    storageBucket: 'agridirect-34e78.firebasestorage.app',
  );
}
